


CREATE TABLE XXBCM_ORDER_MGT_NEW
AS SELECT
    *
FROM
    XXBCM_ORDER_MGT;
	
UPDATE XXBCM_ORDER_MGT_NEW SET ORDER_LINE_AMOUNT = '100000' WHERE ORDER_REF = 'PO002-1' and INVOICE_REFERENCE = 'INV_PO002.1';
UPDATE XXBCM_ORDER_MGT_NEW SET ORDER_LINE_AMOUNT = '5000' WHERE ORDER_REF = 'PO003-3';
UPDATE XXBCM_ORDER_MGT_NEW SET ORDER_LINE_AMOUNT = '1200' WHERE ORDER_REF = 'PO004-2';
UPDATE XXBCM_ORDER_MGT_NEW SET ORDER_LINE_AMOUNT = '30250' WHERE ORDER_REF = 'PO008-1' and INVOICE_REFERENCE = 'INV_PO008.1';
UPDATE XXBCM_ORDER_MGT_NEW SET ORDER_LINE_AMOUNT = '21000' WHERE ORDER_REF = 'PO010-3';
UPDATE XXBCM_ORDER_MGT_NEW SET ORDER_LINE_AMOUNT = '3450' WHERE ORDER_REF = 'PO012-1' and INVOICE_REFERENCE = 'INV_PO012.1';

----
UPDATE XXBCM_ORDER_MGT_NEW SET INVOICE_AMOUNT = '2500' WHERE ORDER_REF = 'PO001-1';
UPDATE XXBCM_ORDER_MGT_NEW SET INVOICE_AMOUNT = '1200' WHERE ORDER_REF = 'PO004-2';
UPDATE XXBCM_ORDER_MGT_NEW SET INVOICE_AMOUNT = '5000' WHERE ORDER_REF = 'PO005-4';

----
UPDATE XXBCM_ORDER_MGT_NEW SET ORDER_DATE = '16-FEB-2022' WHERE ORDER_REF = 'PO006-1' and LENGTH(ORDER_DATE) = 10;
UPDATE XXBCM_ORDER_MGT_NEW SET ORDER_DATE = '03-JUN-2022' WHERE ORDER_REF = 'PO007' and LENGTH(ORDER_DATE) = 10;
UPDATE XXBCM_ORDER_MGT_NEW SET ORDER_DATE = '03-JUL-2022' WHERE ORDER_REF = 'PO010-3' and LENGTH(ORDER_DATE) = 10;
UPDATE XXBCM_ORDER_MGT_NEW SET ORDER_DATE = '06-JUL-2022' WHERE ORDER_REF = 'PO011' and LENGTH(ORDER_DATE) = 10;
UPDATE XXBCM_ORDER_MGT_NEW SET ORDER_DATE = '20-AUG-2022' WHERE ORDER_REF = 'PO013-1' and LENGTH(ORDER_DATE) = 10;
UPDATE XXBCM_ORDER_MGT_NEW SET ORDER_DATE = '15-SEP-2022' WHERE ORDER_REF = 'PO014-2' and LENGTH(ORDER_DATE) = 10;
UPDATE XXBCM_ORDER_MGT_NEW SET ORDER_DATE = '15-SEP-2022' WHERE ORDER_REF = 'PO014-5' and LENGTH(ORDER_DATE) = 10;

----
UPDATE XXBCM_ORDER_MGT_NEW SET INVOICE_DATE = '17-JUN-2022' WHERE INVOICE_REFERENCE = 'INV_PO006.4' and LENGTH(INVOICE_DATE) = 10;
UPDATE XXBCM_ORDER_MGT_NEW SET INVOICE_DATE = '16-AUG-2022' WHERE INVOICE_REFERENCE = 'INV_PO006.6' and LENGTH(INVOICE_DATE) = 10;
UPDATE XXBCM_ORDER_MGT_NEW SET INVOICE_DATE = '18-APR-2022' WHERE INVOICE_REFERENCE = 'INV_PO006.2' and LENGTH(INVOICE_DATE) = 10;
UPDATE XXBCM_ORDER_MGT_NEW SET INVOICE_DATE = '30-JUL-2022' WHERE INVOICE_REFERENCE = 'INV_PO007.1' and LENGTH(INVOICE_DATE) = 10;
UPDATE XXBCM_ORDER_MGT_NEW SET INVOICE_DATE = '28-AUG-2022' WHERE INVOICE_REFERENCE = 'INV_PO008.2' and LENGTH(INVOICE_DATE) = 10;
UPDATE XXBCM_ORDER_MGT_NEW SET INVOICE_DATE = '02-SEP-2022' WHERE INVOICE_REFERENCE = 'INV_PO010.1' and LENGTH(INVOICE_DATE) = 10;
UPDATE XXBCM_ORDER_MGT_NEW SET INVOICE_DATE = '04-SEP-2022' WHERE INVOICE_REFERENCE = 'INV_PO012.2' and LENGTH(INVOICE_DATE) = 10;
UPDATE XXBCM_ORDER_MGT_NEW SET INVOICE_DATE = '28-SEP-2022' WHERE INVOICE_REFERENCE = 'INV_PO013.1' and LENGTH(INVOICE_DATE) = 10;
UPDATE XXBCM_ORDER_MGT_NEW SET INVOICE_DATE = '05-NOV-2022' WHERE INVOICE_REFERENCE = 'INV_PO014.4' and LENGTH(INVOICE_DATE) = 10;
UPDATE XXBCM_ORDER_MGT_NEW SET INVOICE_DATE = '27-OCT-2022' WHERE INVOICE_REFERENCE = 'INV_PO014.3' and LENGTH(INVOICE_DATE) = 10;


----
UPDATE XXBCM_ORDER_MGT_NEW SET SUPP_CONTACT_NUMBER = '5874 1002, 217 4512' WHERE SUPP_CONTACT_NUMBER = '5874 1002, 2I7 4512';
UPDATE XXBCM_ORDER_MGT_NEW SET SUPP_CONTACT_NUMBER = '461 5841, 57412545' WHERE SUPP_CONTACT_NUMBER = '461 5841, 5741254S';
UPDATE XXBCM_ORDER_MGT_NEW SET SUPP_CONTACT_NUMBER = '57841266, 6028010' WHERE SUPP_CONTACT_NUMBER = '57841266, 602801o';

----
UPDATE XXBCM_ORDER_MGT_NEW SET ORDER_LINE_AMOUNT = REPLACE(ORDER_LINE_AMOUNT,',');
UPDATE XXBCM_ORDER_MGT_NEW SET INVOICE_AMOUNT = REPLACE(INVOICE_AMOUNT,',');
UPDATE XXBCM_ORDER_MGT_NEW SET ORDER_TOTAL_AMOUNT = REPLACE(ORDER_TOTAL_AMOUNT,',');

----
ALTER TABLE XXBCM_ORDER_MGT_NEW
  ADD (ORDER_TOTAL_AMOUNT_1 number(10,2));
UPDATE XXBCM_ORDER_MGT_NEW SET ORDER_TOTAL_AMOUNT_1 = TO_NUMBER(ORDER_TOTAL_AMOUNT,'9999999');
ALTER TABLE XXBCM_ORDER_MGT_NEW DROP COLUMN ORDER_TOTAL_AMOUNT;
ALTER TABLE XXBCM_ORDER_MGT_NEW
  RENAME COLUMN ORDER_TOTAL_AMOUNT_1 TO ORDER_TOTAL_AMOUNT;

----  
ALTER TABLE XXBCM_ORDER_MGT_NEW
  ADD (INVOICE_AMOUNT_1 number(10,2));
UPDATE XXBCM_ORDER_MGT_NEW SET INVOICE_AMOUNT_1 = TO_NUMBER(INVOICE_AMOUNT,'9999999');
ALTER TABLE XXBCM_ORDER_MGT_NEW DROP COLUMN INVOICE_AMOUNT;
ALTER TABLE XXBCM_ORDER_MGT_NEW
  RENAME COLUMN INVOICE_AMOUNT_1 TO INVOICE_AMOUNT;
  
----
ALTER TABLE XXBCM_ORDER_MGT_NEW
  ADD (ORDER_LINE_AMOUNT_1 number(10,2));
UPDATE XXBCM_ORDER_MGT_NEW SET ORDER_LINE_AMOUNT_1 = TO_NUMBER(ORDER_LINE_AMOUNT,'9999999');
ALTER TABLE XXBCM_ORDER_MGT_NEW DROP COLUMN ORDER_LINE_AMOUNT;
ALTER TABLE XXBCM_ORDER_MGT_NEW
  RENAME COLUMN ORDER_LINE_AMOUNT_1 TO ORDER_LINE_AMOUNT;   
  
----
ALTER TABLE XXBCM_ORDER_MGT_NEW
  ADD (ORDER_DATE_2 DATE);
UPDATE XXBCM_ORDER_MGT_NEW SET ORDER_DATE_2 = TO_DATE(ORDER_DATE,'DD-MON-YYYY');
ALTER TABLE XXBCM_ORDER_MGT_NEW DROP COLUMN ORDER_DATE;
ALTER TABLE XXBCM_ORDER_MGT_NEW
  RENAME COLUMN ORDER_DATE_2 TO ORDER_DATE;

----
ALTER TABLE XXBCM_ORDER_MGT_NEW
  ADD (SUPPLIER_NAME_2 VARCHAR2 (60));
UPDATE XXBCM_ORDER_MGT_NEW SET SUPPLIER_NAME_2 = SUPPLIER_NAME;
ALTER TABLE XXBCM_ORDER_MGT_NEW DROP COLUMN SUPPLIER_NAME;
ALTER TABLE XXBCM_ORDER_MGT_NEW
  RENAME COLUMN SUPPLIER_NAME_2 TO SUPPLIER_NAME;

----
ALTER TABLE XXBCM_ORDER_MGT_NEW
  ADD (SUPP_CONTACT_NAME_2 VARCHAR2 (60));
UPDATE XXBCM_ORDER_MGT_NEW SET SUPP_CONTACT_NAME_2 = SUPP_CONTACT_NAME;
ALTER TABLE XXBCM_ORDER_MGT_NEW DROP COLUMN SUPP_CONTACT_NAME;
ALTER TABLE XXBCM_ORDER_MGT_NEW
  RENAME COLUMN SUPP_CONTACT_NAME_2 TO SUPP_CONTACT_NAME;

----
ALTER TABLE XXBCM_ORDER_MGT_NEW
  ADD (SUPP_ADDRESS_2 VARCHAR2 (100));
UPDATE XXBCM_ORDER_MGT_NEW SET SUPP_ADDRESS_2 = SUPP_ADDRESS;
ALTER TABLE XXBCM_ORDER_MGT_NEW DROP COLUMN SUPP_ADDRESS;
ALTER TABLE XXBCM_ORDER_MGT_NEW
  RENAME COLUMN SUPP_ADDRESS_2 TO SUPP_ADDRESS;

----
ALTER TABLE XXBCM_ORDER_MGT_NEW
  ADD (SUPP_CONTACT_NUMBER_2 VARCHAR2 (30));
UPDATE XXBCM_ORDER_MGT_NEW SET SUPP_CONTACT_NUMBER_2 = SUPP_CONTACT_NUMBER;
ALTER TABLE XXBCM_ORDER_MGT_NEW DROP COLUMN SUPP_CONTACT_NUMBER;
ALTER TABLE XXBCM_ORDER_MGT_NEW
  RENAME COLUMN SUPP_CONTACT_NUMBER_2 TO SUPP_CONTACT_NUMBER;


----
ALTER TABLE XXBCM_ORDER_MGT_NEW
  ADD (SUPP_EMAIL_2 VARCHAR2 (60));
UPDATE XXBCM_ORDER_MGT_NEW SET SUPP_EMAIL_2 = SUPP_EMAIL;
ALTER TABLE XXBCM_ORDER_MGT_NEW DROP COLUMN SUPP_EMAIL;
ALTER TABLE XXBCM_ORDER_MGT_NEW
  RENAME COLUMN SUPP_EMAIL_2 TO SUPP_EMAIL;  
  

---- 
ALTER TABLE XXBCM_ORDER_MGT_NEW
  ADD (ORDER_DESCRIPTION_2 VARCHAR2 (250));
UPDATE XXBCM_ORDER_MGT_NEW SET ORDER_DESCRIPTION_2 = ORDER_DESCRIPTION;
ALTER TABLE XXBCM_ORDER_MGT_NEW DROP COLUMN ORDER_DESCRIPTION;
ALTER TABLE XXBCM_ORDER_MGT_NEW
  RENAME COLUMN ORDER_DESCRIPTION_2 TO ORDER_DESCRIPTION;
  
----
ALTER TABLE XXBCM_ORDER_MGT_NEW
  ADD (ORDER_STATUS_2 VARCHAR2 (15));
UPDATE XXBCM_ORDER_MGT_NEW SET ORDER_STATUS_2 = ORDER_STATUS;
ALTER TABLE XXBCM_ORDER_MGT_NEW DROP COLUMN ORDER_STATUS;
ALTER TABLE XXBCM_ORDER_MGT_NEW
  RENAME COLUMN ORDER_STATUS_2 TO ORDER_STATUS;
  
  
----
ALTER TABLE XXBCM_ORDER_MGT_NEW
  ADD (INVOICE_REFERENCE_2 VARCHAR2 (30));
UPDATE XXBCM_ORDER_MGT_NEW SET INVOICE_REFERENCE_2 = INVOICE_REFERENCE;
ALTER TABLE XXBCM_ORDER_MGT_NEW DROP COLUMN INVOICE_REFERENCE;
ALTER TABLE XXBCM_ORDER_MGT_NEW
  RENAME COLUMN INVOICE_REFERENCE_2 TO INVOICE_REFERENCE;
  
----
ALTER TABLE XXBCM_ORDER_MGT_NEW
  ADD (INVOICE_DATE_2 DATE);
UPDATE XXBCM_ORDER_MGT_NEW SET INVOICE_DATE_2 = TO_DATE(INVOICE_DATE,'DD-MON-YYYY');
ALTER TABLE XXBCM_ORDER_MGT_NEW DROP COLUMN INVOICE_DATE;
ALTER TABLE XXBCM_ORDER_MGT_NEW
  RENAME COLUMN INVOICE_DATE_2 TO INVOICE_DATE;
  
----
ALTER TABLE XXBCM_ORDER_MGT_NEW
  ADD (INVOICE_STATUS_2 VARCHAR2 (60));
UPDATE XXBCM_ORDER_MGT_NEW SET INVOICE_STATUS_2 = INVOICE_STATUS;
ALTER TABLE XXBCM_ORDER_MGT_NEW DROP COLUMN INVOICE_STATUS;
ALTER TABLE XXBCM_ORDER_MGT_NEW
  RENAME COLUMN INVOICE_STATUS_2 TO INVOICE_STATUS;
  
----
ALTER TABLE XXBCM_ORDER_MGT_NEW
  ADD (INVOICE_HOLD_REASON_2 VARCHAR2 (250));
UPDATE XXBCM_ORDER_MGT_NEW SET INVOICE_HOLD_REASON_2 = INVOICE_HOLD_REASON;
ALTER TABLE XXBCM_ORDER_MGT_NEW DROP COLUMN INVOICE_HOLD_REASON;
ALTER TABLE XXBCM_ORDER_MGT_NEW
  RENAME COLUMN INVOICE_HOLD_REASON_2 TO INVOICE_HOLD_REASON;
  
----
ALTER TABLE XXBCM_ORDER_MGT_NEW
  ADD (INVOICE_DESCRIPTION_2 VARCHAR2 (250));
UPDATE XXBCM_ORDER_MGT_NEW SET INVOICE_DESCRIPTION_2 = INVOICE_DESCRIPTION;
ALTER TABLE XXBCM_ORDER_MGT_NEW DROP COLUMN INVOICE_DESCRIPTION;
ALTER TABLE XXBCM_ORDER_MGT_NEW
  RENAME COLUMN INVOICE_DESCRIPTION_2 TO INVOICE_DESCRIPTION;
  
--Question 3

CREATE TABLE ORDER_TABLE
AS SELECT
    ORDER_REF, ORDER_DATE,	SUPPLIER_NAME,	ORDER_TOTAL_AMOUNT,	ORDER_DESCRIPTION,	ORDER_STATUS
FROM
    XXBCM_ORDER_MGT_NEW
WHERE
    LENGTH(ORDER_REF) = 5;
ALTER TABLE ORDER_TABLE
  ADD (ORDER_REF_2 VARCHAR (5));
UPDATE ORDER_TABLE SET ORDER_REF_2 = ORDER_REF;
ALTER TABLE ORDER_TABLE DROP COLUMN ORDER_REF;
ALTER TABLE ORDER_TABLE
  RENAME COLUMN ORDER_REF_2 TO ORDER_REF;  
  
ALTER TABLE ORDER_TABLE
ADD CONSTRAINT ORDER_REF_PK PRIMARY KEY (ORDER_REF);


----
CREATE TABLE ORDER_LINES_FACT 
AS SELECT
    ORDER_REF,	ORDER_DATE, SUPPLIER_NAME,	ORDER_DESCRIPTION,	ORDER_STATUS,	ORDER_LINE_AMOUNT,	INVOICE_REFERENCE,	INVOICE_DATE,	INVOICE_STATUS,	INVOICE_HOLD_REASON,	INVOICE_AMOUNT,	INVOICE_DESCRIPTION
FROM
    XXBCM_ORDER_MGT_NEW
WHERE
  LENGTH(ORDER_REF) = 7;

ALTER TABLE ORDER_LINES_FACT
  ADD (ORDER_LINE_REF VARCHAR (7));
UPDATE ORDER_LINES_FACT SET ORDER_LINE_REF = ORDER_REF;
ALTER TABLE ORDER_LINES_FACT DROP COLUMN ORDER_REF;

----
ALTER TABLE ORDER_LINES_FACT
  ADD (ORDER_REF VARCHAR (5));
UPDATE ORDER_LINES_FACT SET ORDER_REF = SUBSTR(ORDER_LINE_REF,1,5);

----
CREATE TABLE INVOICE_TABLE 
AS SELECT
    distinct(INVOICE_REFERENCE)
FROM
    XXBCM_ORDER_MGT_NEW
WHERE
    INVOICE_REFERENCE IS NOT NULL;
	
----
ALTER TABLE INVOICE_TABLE
ADD CONSTRAINT INVOICE_REF_PK PRIMARY KEY (INVOICE_REFERENCE);

----
CREATE TABLE SUPPLIER_TABLE 
AS SELECT
    DISTINCT(SUPPLIER_NAME),	SUPP_CONTACT_NAME,	SUPP_ADDRESS,	SUPP_CONTACT_NUMBER, SUPP_EMAIL
FROM
    XXBCM_ORDER_MGT_NEW;
	
----
ALTER TABLE SUPPLIER_TABLE
ADD CONSTRAINT SUPPLIER_ID_PK PRIMARY KEY (SUPPLIER_NAME);

----
ALTER TABLE SUPPLIER_TABLE
  ADD (SUPPLIER_CONTACT_NUMBER_1 VARCHAR (9) ,
       SUPPLIER_CONTACT_NUMBER_2 VARCHAR (9));
	   
----
     
UPDATE SUPPLIER_TABLE SET SUPP_CONTACT_NUMBER = REPLACE(SUPP_CONTACT_NUMBER,' ');
UPDATE SUPPLIER_TABLE SET SUPP_CONTACT_NUMBER = REPLACE(SUPP_CONTACT_NUMBER,'.');

UPDATE SUPPLIER_TABLE SET SUPPLIER_CONTACT_NUMBER_1 = REGEXP_SUBSTR(SUPP_CONTACT_NUMBER, '[^,]+', 1, 1);
UPDATE SUPPLIER_TABLE SET SUPPLIER_CONTACT_NUMBER_2 = REGEXP_SUBSTR (SUPP_CONTACT_NUMBER, '[^,]+', 1, 2);

UPDATE SUPPLIER_TABLE SET SUPPLIER_CONTACT_NUMBER_1 = SUBSTR(SUPPLIER_CONTACT_NUMBER_1,1,4) || '-' || SUBSTR(SUPPLIER_CONTACT_NUMBER_1,5) WHERE LENGTH(SUPPLIER_CONTACT_NUMBER_1) = 8;
UPDATE SUPPLIER_TABLE SET SUPPLIER_CONTACT_NUMBER_1 = SUBSTR(SUPPLIER_CONTACT_NUMBER_1,1,3) || '-' || SUBSTR(SUPPLIER_CONTACT_NUMBER_1,4) WHERE LENGTH(SUPPLIER_CONTACT_NUMBER_1) = 7;

UPDATE SUPPLIER_TABLE SET SUPPLIER_CONTACT_NUMBER_2 = SUBSTR(SUPPLIER_CONTACT_NUMBER_2,1,4) || '-' || SUBSTR(SUPPLIER_CONTACT_NUMBER_2,5) WHERE LENGTH(SUPPLIER_CONTACT_NUMBER_2) = 8;
UPDATE SUPPLIER_TABLE SET SUPPLIER_CONTACT_NUMBER_2 = SUBSTR(SUPPLIER_CONTACT_NUMBER_2,1,3) || '-' || SUBSTR(SUPPLIER_CONTACT_NUMBER_2,4) WHERE LENGTH(SUPPLIER_CONTACT_NUMBER_2) = 7;

----
ALTER TABLE ORDER_LINES_FACT
ADD CONSTRAINT SUPPLIER_FK
  FOREIGN KEY (SUPPLIER_NAME)
  REFERENCES SUPPLIER_TABLE(SUPPLIER_NAME);
  
ALTER TABLE ORDER_LINES_FACT
ADD CONSTRAINT ORDER_REF_FK
  FOREIGN KEY (ORDER_REF)
  REFERENCES ORDER_TABLE(ORDER_REF);  
  
ALTER TABLE ORDER_LINES_FACT
ADD CONSTRAINT INVOICE_FK
  FOREIGN KEY (INVOICE_REFERENCE)
  REFERENCES INVOICE_TABLE(INVOICE_REFERENCE);  
 
commit;